<template>
  <div>
    <h1>博客首页</h1>
    <ul>
      <li>用最简洁的语言～</li>
      <li>写通俗易懂的博客～</li>
      <li>希望你能喜欢～</li>
    </ul>
    <ul>
      <li>注：移动版目录请点击左上角按钮。</li>
    </ul>
  </div>
</template>
